Update Metasploit Installer v1.1, Re-wrote code. Enjoy a faster experience :)

diff --git a/msfinstaller/usr/bin/msfinstaller b/msfinstaller/usr/bin/msfinstaller
--- a/msfinstaller/usr/bin/msfinstaller
+++ b/msfinstaller/usr/bin/msfinstaller
@@ -1,48 +1,33 @@
 #!/bin/bash 
 
-# Reset
-Color_Off='\033[0m'       # Text Reset
+#CREATED BY NOAH LITTLE
+#FOLLOW ON TWITTER @noahacks
 
-# Regular Colors
-Black='\033[0;30m'        # Black
-Red='\033[0;31m'          # Red
-Green='\033[0;32m'        # Green
-Yellow='\033[0;33m'       # Yellow
-Blue='\033[0;34m'         # Blue
-Purple='\033[0;35m'       # Purple
-Cyan='\033[0;36m'         # Cyan
-White='\033[0;37m'        # White
+VER="v1.1"
 
-# Bold
-BBlack='\033[1;30m'       # Black
-Yellowed='\033[1;31m'     # Red
-BGreen='\033[1;32m'       # Green
-BYellow='\033[1;33m'      # Yellow
-BBlue='\033[1;34m'        # Blue
-BPurple='\033[1;35m'      # Purple
-BCyan='\033[1;36m'        # Cyan
-BWhite='\033[1;37m'       # White
+#COLOURS
 
-# Underline
-UBlack='\033[4;30m'       # Black
-URed='\033[4;31m'         # Red
-UGreen='\033[4;32m'       # Green
-UYellow='\033[4;33m'      # Yellow
-UBlue='\033[4;34m'        # Blue
-UPurple='\033[4;35m'      # Purple
-UCyan='\033[4;36m'        # Cyan
-UWhite='\033[4;37m'       # White
+RED='\033[0;31m'
+NC='\033[0m'
+BR='\033[0;33m'
+GR='\033[0;32m'
+LGR='\033[1;32m'
+LRED='\033[1;31m'
+CY='\033[0;36m'
 
-# Background
-On_Black='\033[40m'       # Black
-On_Red='\033[41m'         # Red
-On_Green='\033[42m'       # Green
-On_Yellow='\033[43m'      # Yellow
-On_Blue='\033[44m'        # Blue
-On_Purple='\033[45m'      # Purple
-On_Cyan='\033[46m'        # Cyan
-On_White='\033[47m'       # White
+#TAGS
 
+DBAS=${CY}[**]${NC}
+INFO=${BR}[!]${NC}
+ERROR=${RED}[*${LRED}*${RED}]${NC}
+LOAD=${GR}[*]${NC}
+PROG1="[    ]"
+PROG2="[${GR}>${NC}   ]"
+PROG3="[${GR}=>${NC}  ]"
+PROG4="[${GR}==>${NC} ]"
+PROG5="[${GR}===>${NC}]"
+PROG6="[${GR}DONE${NC}]"
+ENTER="[${CY}>${NC}]"
 
 showLoading() {
   mypid=$!
@@ -51,85 +36,155 @@ showLoading() {
   echo -ne "$Analyzing\r"
 
   while kill -0 $mypid 2>/dev/null; do
-    echo -ne "${Yellow}[!]${Color_Off} $Analyzing.\r"
-    sleep 0.5
-    echo -ne "${Yellow}[!]${Color_Off} $Analyzing..\r"
-    sleep 0.5
-    echo -ne "${Yellow}[!]${Color_Off} $Analyzing...\r"
-    sleep 0.5
+    echo -ne "${LOAD} $Analyzing ${PROG1}\r"
+    sleep 0.1
+    echo -ne "${LOAD} $Analyzing ${PROG2}\r"
+    sleep 0.1
+    echo -ne "${LOAD} $Analyzing ${PROG3}\r"
+    sleep 0.1
+    echo -ne "${LOAD} $Analyzing ${PROG4}\r"
+    sleep 0.1
+    echo -ne "${LOAD} $Analyzing ${PROG5}\r"
+    sleep 0.1
     echo -ne "\r\033[K"
-    echo -ne "${Yellow}[!]${Color_Off} $Analyzing\r"
-    sleep 0.5
+    echo -ne "${LOAD} $Analyzing ${PROG6}\r"
   done
 
-  echo -e "${Yellow}[!]${Color_Off} $Analyzing...${Green}FINISHED${Color_Off}"
+  echo -e "${LOAD} $Analyzing ${PROG6}"
 }
 
+mkdirectory(){
 
-clear & showLoading "Loading msf_installer"
-sleep 2
-echo -e "${Yellow}[!]${Color_Off} Developed by Noah Little (@noahacks)"
-echo -e "${Yellow}[!]${Color_Off} Please don't rebrand this product and re-release!"
+	mkdir /var/msf3/ &> /dev/null
+
+}
+
+cddir(){
+
+	cd /var/msf3/
+
+}
+
+download(){
+
+	wget https://www.dropbox.com/s/78b09mvnxxr10d5/framework-4.2.0.tar.bz2?dl=0 -O framework.tar.bz2 --no-check-certificate
+
+}
+
+extract(){
+
+	tar -xvjf framework.tar.bz2
+
+}
+
+executable(){
+
+	if [ -f /usr/bin/msfconsole ]; then
+
+	rm /usr/bin/msfconsole
+
+	else
+
+	echo "cd /var/msf3/msf/ && ./msfconsole" >> /usr/bin/msfconsole
+
+	fi
+}
+
+perms(){
+
+	chmod +x /usr/bin/msfconsole
+
+}
+
+clean(){
+
+	rm -rf "/var/msf3/framework.tar.bz2"
+
+}
+
+clear
+echo -e "${DBAS} Loading Metasploit Installer"
+sleep 1
+echo -e "${INFO} Developed by Noah Little (@noahacks)"
+echo -e "${INFO} Please don't rebrand this product and re-release!"
 sleep 2
 if [[ $EUID -ne 0 ]]; then
-   echo -e "${Yellow}[!]${Color_Off} msf_installer Failed to gain root privileges.. Exiting" 
-   exit 1
+
+	clear
+	echo -e "${ERROR} Metasploit Installer requires root privileges, please use ${RED}sudo ${0}${NC} Or login as root!"
+	exit 1
+
 fi
 
 #MENU
 
 showMenu(){
 clear
-		echo -e "${On_Red}*****************************************************${On_Black}"
+		echo -e "-----------------------------------------------------"
+		echo -e "${CY}
+                        __ _           _   
+                       / _(_)         | |  
+         _ __ ___  ___| |_ _ _ __  ___| |_ 
+        | '_ ' _ \/ __|  _| | '_ \/ __| __|
+        | | | | | \__ \ | | | | | \__ \ |_ 
+        |_| |_| |_|___/_| |_|_| |_|___/\__|${NC}"
+        echo ""
+		echo "-----------------------------------------------------"
 		echo ""
-		echo -e "${Green}
-                __ _           _   
-               / _(_)         | |  
- _ __ ___  ___| |_ _ _ __  ___| |_ 
-| '_ ' _ \/ __|  _| | '_ \/ __| __|
-| | | | | \__ \ | | | | | \__ \ |_ 
-|_| |_| |_|___/_| |_|_| |_|___/\__|${Color_Off}"
-		echo -e "${Yellowed}By Noah Little (@noahacks)${Color_Off}"
-		echo "msf_installer v1.0.5"
+		echo -e "${BR}[1]${NC} Install Metasploit"
 		echo ""
-		echo -e "${On_Red}*****************************************************${On_Black}"
-		echo -e "${Yellow}[1]${Color_Off} Install Metasploit"
+		echo -e "${BR}[9]${NC} About"
+		echo -e "${BR}[0]${NC} Exit"
+		echo "-----------------------------------------------------"
 		echo ""
-		echo -e "${Yellow}[0]${Color_Off} Exit"
-		read -p "Option: " mc
+		echo -ne "${ENTER} Option: "
+		read -p "" mc
 return $mc
 }
 
 while [[ "$m" != "0" ]]
 do
     if [[ "$m" == "1" ]]; then
+
 	clear
-	echo -e "${Yellow}[!]${Color_Off} Starting Metasploit Installation"
-	echo -e "${Yellow}[!]${Color_Off} Creating Directories"
-	mkdir /var/msf3/
-        echo -e "${Yellow}[!]${Color_Off} Changing Directory"
-	cd /var/msf3/
-	echo -e "${Yellow}[!]${Color_Off} Downloading Data"
+
+	echo -e "${DBAS} Preparing Filesystem"
+
 	sleep 2
-	wget https://www.dropbox.com/s/78b09mvnxxr10d5/framework-4.2.0.tar.bz2?dl=0 -O framework.tar.bz2 --no-check-certificate
-	echo -e "${Yellow}[!]${Color_Off} Downloaded All Data"
-	echo -e "${Yellow}[!]${Color_Off} Extracting MSF_FRAMEWORK"
-	sleep 1
-	tar -xvjf framework.tar.bz2
-	echo -e "${Yellow}[!]${Color_Off} Extracted Data"
-	echo -e "${Yellow}[!]${Color_Off} Creating msfconsole executable."
-	rm /usr/bin/msfconsole
-	sleep 2
-	echo "cd /var/msf3/msf/ && ./msfconsole" >> /usr/bin/msfconsole
-	echo -e "${Yellow}[!]${Color_Off} Created executable"
-	echo -e "${Yellow}[!]${Color_Off} Patching Permissions"
-	chmod +x /usr/bin/msfconsole
-	echo -e "${Yellow}[!]${Color_Off} Cleaning Up"
-	rm -rf /var/msf3/framework.tar.bz2
+
+	mkdirectory & showLoading "Creating Directories"
+
+	cddir & showLoading "Changing Directory"
+
+	download & showLoading "Downloading Data"
+
+	extract & showLoading "Extracting Data"
+
+	executable & showLoading "Creating Executables"
+
+	perms & showLoading "Patching Permissions"
+
+	clean & showLoading "Cleaning Up"
+
 	clear
-	echo -e "${Yellow}[!]${Color_Off} Done."
-	echo -e "${Yellow}[!]${Color_Off} Run the command 'msfconsole' to start metasploit."
-	read -p "Press <Enter> to continue"
+
+	echo -e "${INFO} Completed."
+	echo -e "${INFO} Run the command ${GR}msfconsole${NC} to start Metasploit."
+	echo ""
+	echo -e -n "${ENTER} Press <Enter> to continue"
+	read
+
+elif [[ "$m" == "9" ]]; then
+
+	clear
+
+	echo -e "${INFO} Metasploit Installer ${LGR}${VER}${NC}"
+	echo -e "${INFO} Homepage: ${CY}https://noahlittle.github.com${NC}"
+	echo -e "${INFO} Contact: Twitter ${CY}@noahacks${NC}"
+	echo -e "${INFO} Author: ${CY}Noah Little${NC}"
+	echo ""
+	echo -e -n "${ENTER} Press <Enter> to continue"
+	read
 
 fi
     showMenu
